### ISSUE TITLE
package for Snap/FlatPack/Appimage

### ISSUE THREAD

**Issue by alexanderadam** [emersion/hydroxide#145]
It would be great if there would be one of the distribution _independent_ container image for easy installation.
I guess [the Fedora package is a good start](https://github.com/emersion/hydroxide/issues/118) but it obviously only helps people using Fedora based distributions.

There's some documentation [how to package Snap](https://snapcraft.io/docs/go-applications) or [Flatpak](https://docs.flatpak.org/en/latest/first-build.html).

**PS:** Thank you for your work! :pray:

**Comment by emersion** [comment]
Sorry, I'm not interested in maintaining such a package. Feel free to create a third-party one ofc.

**Comment by schubba** [comment]
Hi everyone,

I’ve been following the long-standing discussions regarding packaging (#118, #145) and systemd integration (#120, #121). Since the earlier efforts seem to have stalled over the last few years, I wanted to share a small project I’ve put together for my own setup to bridge this gap.

Inspired by the work here, I created a GitHub repository that:

Builds daily DEB and RPM packages from the latest stable release using GitHub Actions.

Hosts them in a public repository (Cloudsmith) for easy installation via apt or dnf.

Includes a simplified systemd unit based on the previous community suggestions, but optimized for mobile use (e.g., with K-9 Mail) by allowing flexible IP configuration via an environment file.

This is just a personal effort to keep my own bridge updated automatically, but I thought it might be useful for others who are still looking for a 'set it and forget it' solution as discussed in these threads.

You can find it here: [https://github.com/schubba/hydroxide-repo](https://github.com/schubba/hydroxide-repo)

Many thanks to the original contributors for the initial work and inspiration!
