### ISSUE TITLE
Connecting through tor natively?

### ISSUE THREAD

**Issue by wokawoka** [emersion/hydroxide#150]
Hello guys, it would be great if hydroxide could give the possibility to connect to protonmail natively throug tor, since protonmail supports it (even if I guess it's already possible to do so by setting a HTTPS_PROXY variable at launch).
Was this possibility ever considered? 
Thank you for this great project!

**Comment by emersion** [comment]
What's your plan for implementing this? I'd rather not add a new dependency for Tor.

**Comment by wokawoka** [comment]
The idea is to connect to protonmail through tor to increase the privacy even further.
Protonmail supports tor officially (it just doesn't allow to register at the beginning through tor ) https://protonmail.com/tor

**Comment by PRESFIL** [comment]
You can use socks5-proxy by setting environment variable: #110

**Comment by wokawoka** [comment]
@PRESFIL yes, I did read and follow the other issue, thank you.I just thought that being able to connect through tor (even by default) without having to setup a proxy would have been optimal.

**Comment by emersion** [comment]
I don't think including built-in Tor support is a good idea. It'd be a pretty big dependency if it's at all possible.

**Comment by fisch2** [comment]
Wouldn't be possible to add an option to configure the api endpoint, so that hydroixide uses the tor hidden service https://protonirockerxow.onion/api instead of https://mail.protonmail.com/api ?

**Comment by bruceleerabbit** [comment]
Bug #110 was *apparently* incorrectly implemented. I’ve given some detail here:

https://github.com/emersion/hydroxide/issues/110#issuecomment-1364320184

As far as the bug at hand, I believe what’s missing is a CLI option for specifying a SOCKS proxy. In principle, bug 110 should be re-fixed so that the `http_proxy` var really just supports HTTP proxies. Then bug 150 herein should drive adding a SOCKS CLI option, since not everyone has both an HTTP proxy and a SOCKS proxy. Some people have one and not the other.

Note as well that there is nothing Tor-specific with HTTP proxies or SOCKS proxies. Tor may or may not be involved but Hydroxide certainly need not know about Tor or have any Tor dependencies. So I suggest @emersion reopen this bug.
