### ISSUE TITLE
Ubuntu on Arm

### ISSUE THREAD

**Issue by shadowcyberdeck** [emersion/hydroxide#172]
Does anyone know if this is build-able on Ubuntu Server for Ras Pi4 running Ubuntu Server 20.04.2TLS?  I tried but got some GO errors indicating that the command to build it wasn't available/in that location.

**Comment by emersion** [comment]
Please copy-paste the errors.

**Comment by Marcool04** [comment]
I built this fine on a raspberry pi 4 running Arch Linux Arm. I know it's not Ubuntu but I figure the biggest question mark is the ARM architecture rather than the distro so thought I'd chime in with good news. You could take a look at the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hydroxide) which basically does this:

```bash
export CGO_CPPFLAGS="$CPPFLAGS"
export CGO_CFLAGS="$CFLAGS"
export CGO_CXXFLAGS="$CXXFLAGS"
export CGO_LDFLAGS="$LDFLAGS"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
go build -o build ./cmd/...
````

**Comment by shadowcyberdeck** [comment]
Okay, this was entirely my fault, I decided to start over from scratch.  When I did this the first time I didn't "cd" into the "hydroxide" folder.  Now that I did, it was able to install.
